version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/python:3
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: install moto_server (mock S3)
          command: |
            curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
            chmod 755 /tmp/get-pip.py
            sudo python3 /tmp/get-pip.py
            sudo pip3 install moto[server]

      - restore_cache:
          key: v0001-dependency-cache-{{ .Branch }}-{{ checksum "build.sbt" }}

      - run:
          name: run tests
          command: |
            moto_server s3 -p 9999 &
            cd ~/repo
            sbt clean test

      - save_cache:
          paths:
            - "~/.m2"
            - "~/.sbt"
            - "~/.ivy2"
            - "~/repo/target/resolution-cache"
            - "~/repo/target/streams"
            - "~/repo/project/target/resolution-cache"
            - "~/repo/project/target/streams"
          key: v0001-dependency-cache-{{ .Branch }}-{{ checksum "build.sbt" }}

      - store_test_results:
          path: ~/repo/s3_mocktest_demo/target/test-reports
